---
name: Build and deploy Python app to Azure Web App - recnetemail

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv

      - name: List files
        run: ls -la  # Check the directory contents

      - name: Install dependencies
        run: ./venv/bin/pip install -r requirements.txt  # Use relative path

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*  # Corrected zipping command to include all files

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT
      contents: read  # Required for reading contents

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1395FFC1545D4536A5CCCF11FADC0856 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E6E9EBD4A1BD419B9C88B5AF66D21E86 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BCD9D8A622F8493DBF17AA3FE2AE4346 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'recnetemail'
          slot-name: 'Production'
---
name: Build and deploy Python app to Azure Web App - recnetemail

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv

      - name: List files
        run: ls -la  # Check the directory contents

      - name: Install dependencies
        run: ./venv/bin/pip install -r requirements.txt  # Use relative path

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*  # Corrected zipping command to include all files

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT
      contents: read  # Required for reading contents

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1395FFC1545D4536A5CCCF11FADC0856 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E6E9EBD4A1BD419B9C88B5AF66D21E86 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BCD9D8A622F8493DBF17AA3FE2AE4346 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'recnetemail'
          slot-name: 'Production'
